"""add weekly revenue response portal tables

Revision ID: 0da8141e7158
Revises: da01e91a7cd3
Create Date: 2026-08-14 15:48:15.306865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0da8141e7158'
down_revision: Union[str, Sequence[str], None] = 'da01e91a7cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_revenue_center_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('centre_code', sa.String(), nullable=False),
    sa.Column('centre_name', sa.String(), nullable=False),
    sa.Column('response_token', sa.String(), nullable=True),
    sa.Column('response_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['weekly_revenue_closure_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'centre_code', name='uq_wrc_center_cases_batch_centre')
    )
    with op.batch_alter_table('weekly_revenue_center_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_revenue_center_cases_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_revenue_center_cases_centre_code'), ['centre_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_revenue_center_cases_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_revenue_center_cases_response_token'), ['response_token'], unique=True)

    op.create_table('weekly_revenue_case_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('responder_name', sa.String(), nullable=False),
    sa.Column('responder_npid', sa.String(), nullable=False),
    sa.Column('responder_email', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('selected_center_code', sa.String(), nullable=True),
    sa.Column('selected_center_name', sa.String(), nullable=True),
    sa.Column('evidence_original_filename', sa.String(), nullable=False),
    sa.Column('evidence_mime_type', sa.String(), nullable=False),
    sa.Column('evidence_size_bytes', sa.Integer(), nullable=False),
    sa.Column('evidence_checksum', sa.String(), nullable=False),
    sa.Column('evidence_storage_path', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('was_within_tat', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['weekly_revenue_center_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_revenue_case_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_revenue_case_responses_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_revenue_case_responses_id'), ['id'], unique=False)

    op.create_table('weekly_revenue_center_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('centre_code', sa.String(), nullable=False),
    sa.Column('centre_name', sa.String(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("event_type IN ('opened', 'submitted')", name='ck_wrc_activity_event_type_valid'),
    sa.ForeignKeyConstraint(['case_id'], ['weekly_revenue_center_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_revenue_center_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_revenue_center_activity_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_revenue_center_activity_centre_code'), ['centre_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_revenue_center_activity_id'), ['id'], unique=False)

    with op.batch_alter_table('weekly_revenue_bill_incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
        # Named explicitly -- SQLite batch mode needs a name to reference
        # this constraint later (see e0c78f322c92 / 491aeac1ea3e for the
        # same fix on an earlier unnamed-FK migration).
        batch_op.create_foreign_key(
            'fk_wrc_bill_incidents_reviewed_by_id_users', 'users', ['reviewed_by_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_revenue_bill_incidents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_wrc_bill_incidents_reviewed_by_id_users', type_='foreignkey')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by_id')

    with op.batch_alter_table('weekly_revenue_center_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_revenue_center_activity_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_revenue_center_activity_centre_code'))
        batch_op.drop_index(batch_op.f('ix_weekly_revenue_center_activity_case_id'))

    op.drop_table('weekly_revenue_center_activity')
    with op.batch_alter_table('weekly_revenue_case_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_revenue_case_responses_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_revenue_case_responses_case_id'))

    op.drop_table('weekly_revenue_case_responses')
    with op.batch_alter_table('weekly_revenue_center_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_revenue_center_cases_response_token'))
        batch_op.drop_index(batch_op.f('ix_weekly_revenue_center_cases_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_revenue_center_cases_centre_code'))
        batch_op.drop_index(batch_op.f('ix_weekly_revenue_center_cases_batch_id'))

    op.drop_table('weekly_revenue_center_cases')
    # ### end Alembic commands ###
