"""add delayed cash response portal

Revision ID: 229c43152f64
Revises: e0c78f322c92
Create Date: 2026-08-13 16:44:42.131450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '229c43152f64'
down_revision: Union[str, Sequence[str], None] = 'e0c78f322c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delayed_cash_case_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_penalty_id', sa.Integer(), nullable=False),
    sa.Column('responder_name', sa.String(), nullable=False),
    sa.Column('responder_npid', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_original_filename', sa.String(), nullable=False),
    sa.Column('evidence_mime_type', sa.String(), nullable=False),
    sa.Column('evidence_size_bytes', sa.Integer(), nullable=False),
    sa.Column('evidence_checksum', sa.String(), nullable=False),
    sa.Column('evidence_storage_path', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('was_within_tat', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['center_penalty_id'], ['delayed_cash_center_penalties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delayed_cash_case_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delayed_cash_case_responses_center_penalty_id'), ['center_penalty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delayed_cash_case_responses_id'), ['id'], unique=False)

    with op.batch_alter_table('delayed_cash_center_penalties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('response_token_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_delayed_cash_center_penalties_response_token'), ['response_token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delayed_cash_center_penalties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delayed_cash_center_penalties_response_token'))
        batch_op.drop_column('response_token_expires_at')
        batch_op.drop_column('response_token')

    with op.batch_alter_table('delayed_cash_case_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delayed_cash_case_responses_id'))
        batch_op.drop_index(batch_op.f('ix_delayed_cash_case_responses_center_penalty_id'))

    op.drop_table('delayed_cash_case_responses')
    # ### end Alembic commands ###
