"""add org_dimensions and org_nodes

Revision ID: 2361603621ad
Revises: 74e021c2ce89
Create Date: 2026-08-13 00:22:35.524817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2361603621ad'
down_revision: Union[str, Sequence[str], None] = '74e021c2ce89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_dimensions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_dimensions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_dimensions_key'), ['key'], unique=True)

    op.create_table('org_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dimension_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('external_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dimension_id'], ['org_dimensions.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['org_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dimension_id', 'parent_id', 'name', name='uq_org_node_sibling_name')
    )
    with op.batch_alter_table('org_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_nodes_dimension_id'), ['dimension_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_nodes_external_code'), ['external_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_nodes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_nodes_parent_id'), ['parent_id'], unique=False)

    # ### end Alembic commands ###

    # Seed the default hierarchy template from the product brief. This is
    # dimension *definitions* only -- no actual zone/center/etc. nodes,
    # since no real org data exists yet. Editable/extendable later via the
    # admin dimension-create endpoint; not assumed to be the only valid shape.
    org_dimensions = sa.table(
        'org_dimensions',
        sa.column('key', sa.String),
        sa.column('label', sa.String),
        sa.column('sort_order', sa.Integer),
    )
    op.bulk_insert(
        org_dimensions,
        [
            {"key": "zone", "label": "Zone", "sort_order": 1},
            {"key": "cluster", "label": "Cluster", "sort_order": 2},
            {"key": "region", "label": "Region", "sort_order": 3},
            {"key": "zonal_manager", "label": "Zonal Manager", "sort_order": 4},
            {"key": "regional_manager", "label": "Regional Manager", "sort_order": 5},
            {"key": "center", "label": "Center", "sort_order": 6},
            {"key": "employee", "label": "Employee", "sort_order": 7},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_nodes_parent_id'))
        batch_op.drop_index(batch_op.f('ix_org_nodes_id'))
        batch_op.drop_index(batch_op.f('ix_org_nodes_external_code'))
        batch_op.drop_index(batch_op.f('ix_org_nodes_dimension_id'))

    op.drop_table('org_nodes')
    with op.batch_alter_table('org_dimensions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_dimensions_key'))
        batch_op.drop_index(batch_op.f('ix_org_dimensions_id'))

    op.drop_table('org_dimensions')
    # ### end Alembic commands ###
