"""add no_remark_role_penalty_scope to wrc rules

Revision ID: 24fa802b1040
Revises: 5ba0753378dc
Create Date: 2026-08-17 18:52:55.320834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24fa802b1040'
down_revision: Union[str, Sequence[str], None] = '5ba0753378dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_revenue_closure_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_remark_role_penalty_scope', sa.String(), server_default='all_types', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_revenue_closure_rules', schema=None) as batch_op:
        batch_op.drop_column('no_remark_role_penalty_scope')

    # ### end Alembic commands ###
