"""add delayed cash billing penalty engine

Revision ID: 2953eb93efa3
Revises: 3ebb2bec87f1
Create Date: 2026-08-13 16:16:53.368933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2953eb93efa3'
down_revision: Union[str, Sequence[str], None] = '3ebb2bec87f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delayed_cash_penalty_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_version', sa.String(), nullable=False),
    sa.Column('rate_per_day', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monthly_cap_percentage', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'approved')", name='ck_dcb_rules_status_valid'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delayed_cash_penalty_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delayed_cash_penalty_rules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delayed_cash_penalty_rules_rule_version'), ['rule_version'], unique=True)

    op.create_table('delayed_cash_upload_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('source_filename', sa.String(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('uploaded', 'published', 'closed')", name='ck_dcb_batches_status_valid'),
    sa.ForeignKeyConstraint(['rule_id'], ['delayed_cash_penalty_rules.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delayed_cash_upload_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delayed_cash_upload_batches_id'), ['id'], unique=False)

    op.create_table('delayed_cash_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('centre_code', sa.String(), nullable=False),
    sa.Column('centre_name', sa.String(), nullable=False),
    sa.Column('sales_bill', sa.String(), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('bill_created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('source_day_difference', sa.Integer(), nullable=False),
    sa.Column('center_remarks', sa.Text(), nullable=True),
    sa.Column('penalty_remarks', sa.Text(), nullable=True),
    sa.Column('calculated_day_difference', sa.Integer(), nullable=False),
    sa.Column('difference_check', sa.String(), nullable=False),
    sa.Column('data_quality_status', sa.String(), nullable=False),
    sa.Column('calculated_penalty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('considered', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("data_quality_status IN ('ok', 'flagged')", name='ck_dcb_bills_quality_valid'),
    sa.CheckConstraint("difference_check IN ('match', 'mismatch')", name='ck_dcb_bills_diff_check_valid'),
    sa.ForeignKeyConstraint(['batch_id'], ['delayed_cash_upload_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'sales_bill', name='uq_dcb_bills_batch_salesbill')
    )
    with op.batch_alter_table('delayed_cash_bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delayed_cash_bills_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delayed_cash_bills_centre_code'), ['centre_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_delayed_cash_bills_id'), ['id'], unique=False)

    op.create_table('delayed_cash_center_penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('centre_code', sa.String(), nullable=False),
    sa.Column('centre_name', sa.String(), nullable=False),
    sa.Column('total_bills', sa.Integer(), nullable=False),
    sa.Column('calculated_penalty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('validated_penalty', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('monthly_cap_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('final_penalty', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('penalty_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("penalty_status IN ('published', 'validated', 'awaiting_cap_input', 'capped')", name='ck_dcb_center_penalties_status_valid'),
    sa.ForeignKeyConstraint(['batch_id'], ['delayed_cash_upload_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'centre_code', name='uq_dcb_center_penalties_batch_centre')
    )
    with op.batch_alter_table('delayed_cash_center_penalties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delayed_cash_center_penalties_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delayed_cash_center_penalties_centre_code'), ['centre_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_delayed_cash_center_penalties_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delayed_cash_center_penalties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delayed_cash_center_penalties_id'))
        batch_op.drop_index(batch_op.f('ix_delayed_cash_center_penalties_centre_code'))
        batch_op.drop_index(batch_op.f('ix_delayed_cash_center_penalties_batch_id'))

    op.drop_table('delayed_cash_center_penalties')
    with op.batch_alter_table('delayed_cash_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delayed_cash_bills_id'))
        batch_op.drop_index(batch_op.f('ix_delayed_cash_bills_centre_code'))
        batch_op.drop_index(batch_op.f('ix_delayed_cash_bills_batch_id'))

    op.drop_table('delayed_cash_bills')
    with op.batch_alter_table('delayed_cash_upload_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delayed_cash_upload_batches_id'))

    op.drop_table('delayed_cash_upload_batches')
    with op.batch_alter_table('delayed_cash_penalty_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delayed_cash_penalty_rules_rule_version'))
        batch_op.drop_index(batch_op.f('ix_delayed_cash_penalty_rules_id'))

    op.drop_table('delayed_cash_penalty_rules')
    # ### end Alembic commands ###
