"""add reconciliations

Revision ID: 33d7545bfe3a
Revises: f095fbfd2a99
Create Date: 2026-08-13 11:36:17.888363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d7545bfe3a'
down_revision: Union[str, Sequence[str], None] = 'f095fbfd2a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_a_id', sa.Integer(), nullable=False),
    sa.Column('dataset_b_id', sa.Integer(), nullable=False),
    sa.Column('key_column_a', sa.String(), nullable=False),
    sa.Column('key_column_b', sa.String(), nullable=False),
    sa.Column('compare_columns', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('matched_count', sa.Integer(), nullable=True),
    sa.Column('mismatched_count', sa.Integer(), nullable=True),
    sa.Column('missing_in_b_count', sa.Integer(), nullable=True),
    sa.Column('extra_in_b_count', sa.Integer(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('run_by_id', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('completed', 'failed')", name='ck_reconciliations_status_valid'),
    sa.ForeignKeyConstraint(['dataset_a_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['dataset_b_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['run_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconciliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliations_dataset_a_id'), ['dataset_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliations_dataset_b_id'), ['dataset_b_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliations_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reconciliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliations_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliations_dataset_b_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliations_dataset_a_id'))

    op.drop_table('reconciliations')
    # ### end Alembic commands ###
