"""add email connection tables

Revision ID: 3ebb2bec87f1
Revises: a6d1c8ebf82b
Create Date: 2026-08-13 14:17:24.647178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ebb2bec87f1'
down_revision: Union[str, Sequence[str], None] = 'a6d1c8ebf82b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_connection_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_connection_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_connection_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_connection_requests_state_token'), ['state_token'], unique=True)

    op.create_table('email_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('encrypted_access_token', sa.String(), nullable=True),
    sa.Column('encrypted_refresh_token', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("provider IN ('gmail')", name='ck_email_connections_provider_valid'),
    sa.CheckConstraint("status IN ('connected', 'revoked')", name='ck_email_connections_status_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_connections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_connections_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_connections_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_connections_id'))

    op.drop_table('email_connections')
    with op.batch_alter_table('email_connection_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_connection_requests_state_token'))
        batch_op.drop_index(batch_op.f('ix_email_connection_requests_id'))

    op.drop_table('email_connection_requests')
    # ### end Alembic commands ###
