"""add org node contact change requests and responder email

Revision ID: 4240f22ada49
Revises: c8c0a83e95dd
Create Date: 2026-08-13 18:51:26.154738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4240f22ada49'
down_revision: Union[str, Sequence[str], None] = 'c8c0a83e95dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_node_contact_change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_node_id', sa.Integer(), nullable=True),
    sa.Column('centre_code_hint', sa.String(), nullable=False),
    sa.Column('proposed_manager_name', sa.String(), nullable=True),
    sa.Column('proposed_manager_npid', sa.String(), nullable=True),
    sa.Column('proposed_manager_email', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_reference_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_org_contact_change_status_valid'),
    sa.ForeignKeyConstraint(['org_node_id'], ['org_nodes.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_node_contact_change_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_node_contact_change_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_node_contact_change_requests_org_node_id'), ['org_node_id'], unique=False)

    with op.batch_alter_table('delayed_cash_case_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responder_email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delayed_cash_case_responses', schema=None) as batch_op:
        batch_op.drop_column('responder_email')

    with op.batch_alter_table('org_node_contact_change_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_node_contact_change_requests_org_node_id'))
        batch_op.drop_index(batch_op.f('ix_org_node_contact_change_requests_id'))

    op.drop_table('org_node_contact_change_requests')
    # ### end Alembic commands ###
