"""add audits findings evidence and users.org_node_id

Revision ID: 491aeac1ea3e
Revises: 2361603621ad
Create Date: 2026-08-13 10:44:02.461585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '491aeac1ea3e'
down_revision: Union[str, Sequence[str], None] = '2361603621ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('center_node_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("priority IN ('Low', 'Medium', 'High', 'Critical')", name='ck_audits_priority_valid'),
    sa.CheckConstraint("status IN ('Draft', 'Assigned', 'In Progress', 'Under Review', 'Action Required', 'Closed', 'Cancelled')", name='ck_audits_status_valid'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['center_node_id'], ['org_nodes.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audits_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audits_audit_number'), ['audit_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_audits_center_node_id'), ['center_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audits_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audits_id'), ['id'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('finding_number', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('financial_exposure', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('recoverable_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("severity IN ('Low', 'Medium', 'High', 'Critical')", name='ck_findings_severity_valid'),
    sa.CheckConstraint("status IN ('Open', 'Under Review', 'Action Required', 'Resolved', 'Closed')", name='ck_findings_status_valid'),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_finding_number'), ['finding_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_findings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_owner_id'), ['owner_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=True),
    sa.Column('finding_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('audit_id IS NOT NULL OR finding_id IS NOT NULL', name='ck_evidence_has_owner'),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_uploaded_by_id'), ['uploaded_by_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_node_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_org_node_id'), ['org_node_id'], unique=False)
        # autogenerate emits create_foreign_key(None, ...) but SQLite batch
        # mode requires every constraint to have an explicit name (it has
        # to track it through the table-recreate); named it explicitly.
        batch_op.create_foreign_key(
            'fk_users_org_node_id_org_nodes', 'org_nodes', ['org_node_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_org_node_id_org_nodes', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_org_node_id'))
        batch_op.drop_column('org_node_id')

    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_uploaded_by_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_finding_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_audit_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_owner_id'))
        batch_op.drop_index(batch_op.f('ix_findings_id'))
        batch_op.drop_index(batch_op.f('ix_findings_finding_number'))
        batch_op.drop_index(batch_op.f('ix_findings_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_findings_audit_id'))

    op.drop_table('findings')
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audits_id'))
        batch_op.drop_index(batch_op.f('ix_audits_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_audits_center_node_id'))
        batch_op.drop_index(batch_op.f('ix_audits_audit_number'))
        batch_op.drop_index(batch_op.f('ix_audits_assigned_to_id'))

    op.drop_table('audits')
    # ### end Alembic commands ###
