"""add escalation_sms_sent_at

Revision ID: 5ba0753378dc
Revises: 9dc4fab8a2bc
Create Date: 2026-08-17 18:14:59.409997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba0753378dc'
down_revision: Union[str, Sequence[str], None] = '9dc4fab8a2bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delayed_cash_center_penalties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('escalation_sms_sent_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('weekly_revenue_center_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('escalation_sms_sent_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_revenue_center_cases', schema=None) as batch_op:
        batch_op.drop_column('escalation_sms_sent_at')

    with op.batch_alter_table('delayed_cash_center_penalties', schema=None) as batch_op:
        batch_op.drop_column('escalation_sms_sent_at')

    # ### end Alembic commands ###
