"""add org node manager contact fields

Revision ID: 5ef7674c9920
Revises: ed77aceda547
Create Date: 2026-08-13 17:23:44.724059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef7674c9920'
down_revision: Union[str, Sequence[str], None] = 'ed77aceda547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('manager_email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('manager_phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('manager_npid', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_nodes', schema=None) as batch_op:
        batch_op.drop_column('manager_npid')
        batch_op.drop_column('manager_phone')
        batch_op.drop_column('manager_email')
        batch_op.drop_column('manager_name')

    # ### end Alembic commands ###
