"""add report_templates and report_history

Revision ID: 9db0ab5e5756
Revises: 3b2fdb5c0acd
Create Date: 2026-08-13 12:54:52.958054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db0ab5e5756'
down_revision: Union[str, Sequence[str], None] = '3b2fdb5c0acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_templates_id'), ['id'], unique=False)

    op.create_table('report_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('filters_used', sa.JSON(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('generated_by_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('regenerated_from_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("format IN ('csv', 'xlsx', 'pdf')", name='ck_report_history_format_valid'),
    sa.CheckConstraint("status IN ('completed', 'failed')", name='ck_report_history_status_valid'),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['regenerated_from_id'], ['report_history.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_history_template_id'), ['template_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_history_template_id'))
        batch_op.drop_index(batch_op.f('ix_report_history_id'))

    op.drop_table('report_history')
    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_templates_id'))

    op.drop_table('report_templates')
    # ### end Alembic commands ###
