"""add center_scoring_weights

Revision ID: a6d1c8ebf82b
Revises: 2429c5648d8c
Create Date: 2026-08-13 14:00:05.722181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d1c8ebf82b'
down_revision: Union[str, Sequence[str], None] = '2429c5648d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('center_scoring_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_key', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("component_key IN ('financial_exposure', 'recovery_rate', 'open_findings', 'repeat_findings')", name='ck_center_scoring_component_valid'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('center_scoring_weights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_center_scoring_weights_component_key'), ['component_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_center_scoring_weights_id'), ['id'], unique=False)

    # ### end Alembic commands ###

    # EQUAL weights across the 4 components the user chose (2026-08-13,
    # "start with equal weights, I'll adjust later") -- a documented
    # placeholder the user asked for, not an invented business answer.
    # Change via PATCH /center-scoring/weights/{component_key}, no migration needed.
    center_scoring_weights = sa.table(
        'center_scoring_weights',
        sa.column('component_key', sa.String),
        sa.column('weight', sa.Float),
    )
    op.bulk_insert(
        center_scoring_weights,
        [
            {"component_key": "financial_exposure", "weight": 0.25},
            {"component_key": "recovery_rate", "weight": 0.25},
            {"component_key": "open_findings", "weight": 0.25},
            {"component_key": "repeat_findings", "weight": 0.25},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('center_scoring_weights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_center_scoring_weights_id'))
        batch_op.drop_index(batch_op.f('ix_center_scoring_weights_component_key'))

    op.drop_table('center_scoring_weights')
    # ### end Alembic commands ###
