"""add selected center fields to delayed cash case response

Revision ID: bb2c0b897e5a
Revises: 52e34c0c400c
Create Date: 2026-08-13 17:36:12.394632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb2c0b897e5a'
down_revision: Union[str, Sequence[str], None] = '52e34c0c400c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delayed_cash_case_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_center_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('selected_center_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delayed_cash_case_responses', schema=None) as batch_op:
        batch_op.drop_column('selected_center_name')
        batch_op.drop_column('selected_center_code')

    # ### end Alembic commands ###
