"""add bill review decision columns and constraint

Revision ID: c8c0a83e95dd
Revises: bb2c0b897e5a
Create Date: 2026-08-13 18:48:10.341692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8c0a83e95dd'
down_revision: Union[str, Sequence[str], None] = 'bb2c0b897e5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('delayed_cash_bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
        # Explicitly named -- an unnamed FK constraint breaks SQLite batch
        # mode on a later migration that needs to recreate this table.
        batch_op.create_foreign_key(
            'fk_dcb_bills_reviewed_by_id_users', 'users', ['reviewed_by_id'], ['id']
        )
        # Not autogenerated -- Alembic's SQLite autogenerate doesn't detect
        # CHECK constraint changes. Verified beforehand: every existing row's
        # `considered` value in the live DB is NULL, so widening the allowed
        # set is safe with zero backfill needed.
        batch_op.create_check_constraint(
            'ck_dcb_bills_considered_valid',
            "considered IS NULL OR considered IN ('considered', 'not_considered', 'needs_more_detail', 'needs_proof')",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('delayed_cash_bills', schema=None) as batch_op:
        batch_op.drop_constraint('ck_dcb_bills_considered_valid', type_='check')
        batch_op.drop_constraint('fk_dcb_bills_reviewed_by_id_users', type_='foreignkey')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by_id')

    # ### end Alembic commands ###
