"""add weekly revenue closure domain

Revision ID: cbcd5d2613fa
Revises: 4240f22ada49
Create Date: 2026-08-13 21:49:59.841146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbcd5d2613fa'
down_revision: Union[str, Sequence[str], None] = '4240f22ada49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_revenue_closure_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_version', sa.String(), nullable=False),
    sa.Column('penalty_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'approved')", name='ck_wrc_rules_status_valid'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_revenue_closure_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_revenue_closure_rules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_revenue_closure_rules_rule_version'), ['rule_version'], unique=True)

    op.create_table('weekly_revenue_closure_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('week_label', sa.String(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'closed')", name='ck_wrc_batches_status_valid'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['weekly_revenue_closure_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_revenue_closure_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_revenue_closure_batches_id'), ['id'], unique=False)

    op.create_table('weekly_revenue_bill_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('centre_code', sa.String(), nullable=False),
    sa.Column('centre_name', sa.String(), nullable=False),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('cluster', sa.String(), nullable=True),
    sa.Column('zonal_manager', sa.String(), nullable=True),
    sa.Column('center_manager', sa.String(), nullable=True),
    sa.Column('center_manager_npid', sa.String(), nullable=True),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('billed_sessions', sa.Integer(), nullable=True),
    sa.Column('daily_report', sa.Integer(), nullable=True),
    sa.Column('variance', sa.Integer(), nullable=True),
    sa.Column('raw_remark', sa.String(), nullable=True),
    sa.Column('mis_final_remark', sa.String(), nullable=False),
    sa.Column('center_remarks', sa.Text(), nullable=True),
    sa.Column('penalty_remarks', sa.Text(), nullable=True),
    sa.Column('considered', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("considered IS NULL OR considered IN ('considered', 'not_considered')", name='ck_wrc_bill_incidents_considered_valid'),
    sa.CheckConstraint("mis_final_remark IN ('bill_pending', 'daily_report_not_sent', 'no_billing_no_daily_report')", name='ck_wrc_bill_incidents_mis_remark_valid'),
    sa.ForeignKeyConstraint(['batch_id'], ['weekly_revenue_closure_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_revenue_bill_incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_revenue_bill_incidents_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_revenue_bill_incidents_centre_code'), ['centre_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_revenue_bill_incidents_id'), ['id'], unique=False)

    op.create_table('weekly_revenue_center_penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('centre_code', sa.String(), nullable=False),
    sa.Column('centre_name', sa.String(), nullable=False),
    sa.Column('center_manager', sa.String(), nullable=True),
    sa.Column('center_manager_npid', sa.String(), nullable=True),
    sa.Column('not_considered_penalty', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('no_remark_penalty', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['weekly_revenue_closure_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'centre_code', name='uq_wrc_center_penalties_batch_centre')
    )
    with op.batch_alter_table('weekly_revenue_center_penalties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_revenue_center_penalties_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_revenue_center_penalties_centre_code'), ['centre_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_revenue_center_penalties_id'), ['id'], unique=False)

    op.create_table('weekly_revenue_no_remark_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('centre_code', sa.String(), nullable=False),
    sa.Column('centre_name', sa.String(), nullable=False),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('cluster', sa.String(), nullable=True),
    sa.Column('zonal_manager', sa.String(), nullable=True),
    sa.Column('center_manager', sa.String(), nullable=True),
    sa.Column('center_manager_npid', sa.String(), nullable=True),
    sa.Column('incident_type', sa.String(), nullable=False),
    sa.Column('incident_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("incident_type IN ('bill_pending', 'daily_report_not_sent', 'no_billing_no_daily_report')", name='ck_wrc_no_remark_incident_type_valid'),
    sa.ForeignKeyConstraint(['batch_id'], ['weekly_revenue_closure_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'centre_code', 'incident_type', name='uq_wrc_no_remark_batch_centre_type')
    )
    with op.batch_alter_table('weekly_revenue_no_remark_incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_revenue_no_remark_incidents_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_revenue_no_remark_incidents_centre_code'), ['centre_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_revenue_no_remark_incidents_id'), ['id'], unique=False)

    op.create_table('weekly_revenue_role_penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('person_name', sa.String(), nullable=False),
    sa.Column('person_npid', sa.String(), nullable=True),
    sa.Column('distinct_center_count', sa.Integer(), nullable=False),
    sa.Column('penalty_amount', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('cluster_manager', 'zonal_manager')", name='ck_wrc_role_penalties_role_valid'),
    sa.CheckConstraint("section IN ('not_considered', 'no_remark')", name='ck_wrc_role_penalties_section_valid'),
    sa.ForeignKeyConstraint(['batch_id'], ['weekly_revenue_closure_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'role', 'person_npid', 'section', name='uq_wrc_role_penalties_batch_role_person_section')
    )
    with op.batch_alter_table('weekly_revenue_role_penalties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_revenue_role_penalties_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_revenue_role_penalties_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_revenue_role_penalties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_revenue_role_penalties_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_revenue_role_penalties_batch_id'))

    op.drop_table('weekly_revenue_role_penalties')
    with op.batch_alter_table('weekly_revenue_no_remark_incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_revenue_no_remark_incidents_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_revenue_no_remark_incidents_centre_code'))
        batch_op.drop_index(batch_op.f('ix_weekly_revenue_no_remark_incidents_batch_id'))

    op.drop_table('weekly_revenue_no_remark_incidents')
    with op.batch_alter_table('weekly_revenue_center_penalties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_revenue_center_penalties_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_revenue_center_penalties_centre_code'))
        batch_op.drop_index(batch_op.f('ix_weekly_revenue_center_penalties_batch_id'))

    op.drop_table('weekly_revenue_center_penalties')
    with op.batch_alter_table('weekly_revenue_bill_incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_revenue_bill_incidents_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_revenue_bill_incidents_centre_code'))
        batch_op.drop_index(batch_op.f('ix_weekly_revenue_bill_incidents_batch_id'))

    op.drop_table('weekly_revenue_bill_incidents')
    with op.batch_alter_table('weekly_revenue_closure_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_revenue_closure_batches_id'))

    op.drop_table('weekly_revenue_closure_batches')
    with op.batch_alter_table('weekly_revenue_closure_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_revenue_closure_rules_rule_version'))
        batch_op.drop_index(batch_op.f('ix_weekly_revenue_closure_rules_id'))

    op.drop_table('weekly_revenue_closure_rules')
    # ### end Alembic commands ###
