"""add cluster manager role and org node is_active

Revision ID: e0c78f322c92
Revises: 2953eb93efa3
Create Date: 2026-08-13 16:29:09.978574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c78f322c92'
down_revision: Union[str, Sequence[str], None] = '2953eb93efa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###

    # Hand-added: autogenerate does not detect CHECK constraint changes on
    # SQLite, so the users.role CHECK must be widened by hand to admit the
    # new "Cluster Manager" role. Named constraint, batch mode (SQLite
    # requires recreating the table to alter a CHECK) -- see backend/README.md
    # for why an unnamed constraint here would break batch mode.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('ck_users_role_valid', type_='check')
        batch_op.create_check_constraint(
            'ck_users_role_valid',
            "role IN ('Admin', 'Auditor', 'Finance', 'Center Manager', 'Cluster Manager', "
            "'Regional Manager', 'Zonal Manager')",
        )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('ck_users_role_valid', type_='check')
        batch_op.create_check_constraint(
            'ck_users_role_valid',
            "role IN ('Admin', 'Auditor', 'Finance', 'Center Manager', 'Regional Manager', 'Zonal Manager')",
        )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_nodes', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
