"""add penalty_rules penalties recoveries

Revision ID: f095fbfd2a99
Revises: a89f2e53a82d
Create Date: 2026-08-13 11:26:10.728054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f095fbfd2a99'
down_revision: Union[str, Sequence[str], None] = 'a89f2e53a82d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penalty_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('formula_config', sa.JSON(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('penalty_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_penalty_rules_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_penalty_rules_id'), ['id'], unique=False)

    op.create_table('penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('penalty_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('proposed_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('Proposed', 'Approved', 'Rejected', 'Recovered')", name='ck_penalties_status_valid'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['proposed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['penalty_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('penalties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_penalties_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_penalties_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_penalties_rule_id'), ['rule_id'], unique=False)

    op.create_table('recoveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('penalty_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['penalty_id'], ['penalties.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recoveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recoveries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recoveries_penalty_id'), ['penalty_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recoveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recoveries_penalty_id'))
        batch_op.drop_index(batch_op.f('ix_recoveries_id'))

    op.drop_table('recoveries')
    with op.batch_alter_table('penalties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_penalties_rule_id'))
        batch_op.drop_index(batch_op.f('ix_penalties_id'))
        batch_op.drop_index(batch_op.f('ix_penalties_finding_id'))

    op.drop_table('penalties')
    with op.batch_alter_table('penalty_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_penalty_rules_id'))
        batch_op.drop_index(batch_op.f('ix_penalty_rules_code'))

    op.drop_table('penalty_rules')
    # ### end Alembic commands ###
